"""Internal C++ extension package.

This package wraps the compiled extension module (built via pybind11).

Public users should import symbols from the top-level `biotransport` package.
"""

from ._core import (
    Boundary,
    BoundaryCondition,
    BoundaryType,
    DiffusionSolver,
    CrankNicolsonDiffusion,
    CNSolveResult,
    ConstantSourceReactionDiffusionSolver,
    ExplicitFD,
    TransportProblem,
    GrayScottRunResult,
    GrayScottSolver,
    TumorDrugDeliverySaved,
    TumorDrugDeliverySolver,
    BioheatCryotherapySolver,
    BioheatSaved,
    LinearReactionDiffusionSolver,
    LogisticReactionDiffusionSolver,
    MichaelisMentenReactionDiffusionSolver,
    MaskedMichaelisMentenReactionDiffusionSolver,
    ReactionDiffusionSolver,
    RunResult,
    SolverStats,
    StructuredMesh,
    # Advection-diffusion (Phase 2)
    AdvectionScheme,
    AdvectionDiffusionSolver,
    # Darcy flow (Phase 3)
    DarcyFlowResult,
    DarcyFlowSolver,
    # Membrane diffusion (Phase 4)
    MembraneDiffusionResult,
    MembraneDiffusion1DSolver,
    MultiLayerMembraneSolver,
    renkin_hindrance,
    # Submodules
    dimensionless,
    analytical,
    # Fluid dynamics (Stokes & Navier-Stokes)
    VelocityBCType,
    VelocityBC,
    StokesResult,
    StokesSolver,
    ConvectionScheme,
    NavierStokesResult,
    NavierStokesSolver,
    # Cylindrical mesh
    CylindricalMeshType,
    CylindricalMesh,
    # Non-Newtonian fluid models
    FluidModel,
    ViscosityModel,
    NewtonianModel,
    PowerLawModel,
    CarreauModel,
    CarreauYasudaModel,
    CrossModel,
    BinghamModel,
    HerschelBulkleyModel,
    CassonModel,
    # Blood rheology utilities
    blood_casson_model,
    blood_carreau_model,
    pipe_wall_shear_rate,
)

__all__ = [
    "StructuredMesh",
    "DiffusionSolver",
    "CrankNicolsonDiffusion",
    "CNSolveResult",
    "ConstantSourceReactionDiffusionSolver",
    "LinearReactionDiffusionSolver",
    "LogisticReactionDiffusionSolver",
    "MichaelisMentenReactionDiffusionSolver",
    "ReactionDiffusionSolver",
    "MaskedMichaelisMentenReactionDiffusionSolver",
    "BoundaryType",
    "Boundary",
    "BoundaryCondition",
    "TransportProblem",
    "ExplicitFD",
    "RunResult",
    "GrayScottSolver",
    "GrayScottRunResult",
    "TumorDrugDeliverySolver",
    "TumorDrugDeliverySaved",
    "BioheatCryotherapySolver",
    "BioheatSaved",
    "SolverStats",
    "AdvectionScheme",
    "AdvectionDiffusionSolver",
    "DarcyFlowResult",
    "DarcyFlowSolver",
    "MembraneDiffusionResult",
    "MembraneDiffusion1DSolver",
    "MultiLayerMembraneSolver",
    "renkin_hindrance",
    "dimensionless",
    "analytical",
    # Fluid dynamics (Stokes & Navier-Stokes)
    "VelocityBCType",
    "VelocityBC",
    "StokesResult",
    "StokesSolver",
    "ConvectionScheme",
    "NavierStokesResult",
    "NavierStokesSolver",
    # Cylindrical mesh
    "CylindricalMeshType",
    "CylindricalMesh",
    # Non-Newtonian fluid models
    "FluidModel",
    "ViscosityModel",
    "NewtonianModel",
    "PowerLawModel",
    "CarreauModel",
    "CarreauYasudaModel",
    "CrossModel",
    "BinghamModel",
    "HerschelBulkleyModel",
    "CassonModel",
    # Blood rheology utilities
    "blood_casson_model",
    "blood_carreau_model",
    "pipe_wall_shear_rate",
]
