"""Internal C++ extension package.

This package wraps the compiled extension module (built via pybind11).

Public users should import symbols from the top-level `biotransport` package.
"""

from ._core import (
    BalanceDimension,
    BalanceUnit,
    BalanceTransferDirection,
    BalanceTerm,
    BalanceTransfer,
    BalanceAudit,
    BalanceLedger,
    MatchedBalanceTransfer,
    DimensionBalanceAudit,
    BalanceReconciliation,
    balance_dimension_name,
    balance_unit_symbol,
    balance_unit_dimension,
    balance_base_unit,
    convert_balance_value,
    reconcile_balances,
    native_build_info,
    NonuniformMesh1D,
    NonuniformDiffusionDiagnostics,
    NonuniformDiffusion1D,
    Boundary,
    Boundary3D,
    BoundaryCondition,
    BoundaryType,
    DiffusionSolver,
    DiffusionSolver3D,
    LinearReactionDiffusionSolver3D,
    CrankNicolsonDiffusion,
    CNSolveResult,
    # ADI solvers
    ADIDiffusion2D,
    ADIDiffusion3D,
    ADISolveResult,
    # Sparse matrix and implicit solvers
    SparseSolverType,
    SparseSolveResult,
    Triplet,
    SparseMatrix,
    build_2d_laplacian,
    build_implicit_diffusion_2d,
    build_implicit_diffusion_3d,
    ImplicitSolveResult,
    ImplicitDiffusion2D,
    ImplicitDiffusion3D,
    sparse_matrix_available,
    ConstantSourceReactionDiffusionSolver,
    ExplicitFD,
    TransportProblem,
    GrayScottRunResult,
    GrayScottSolver,
    TumorDrugDeliverySaved,
    TumorDrugDeliverySolver,
    BioheatCryotherapySolver,
    BioheatSaved,
    LinearReactionDiffusionSolver,
    LogisticReactionDiffusionSolver,
    MichaelisMentenReactionDiffusionSolver,
    MaskedMichaelisMentenReactionDiffusionSolver,
    ReactionDiffusionSolver,
    RunResult,
    SolverStats,
    SolveOptions,
    SolveDiagnostics,
    TransportResult,
    solve_transport,
    StructuredMesh,
    StructuredMesh3D,
    # Higher-order finite difference stencils
    StencilOps,
    # Advection-diffusion (Phase 2)
    AdvectionScheme,
    AdvectionDiffusionSolver,
    # Darcy flow (Phase 3)
    DarcyFlowResult,
    DarcyFlowSolver,
    # Membrane diffusion (Phase 4)
    MembraneDiffusionResult,
    MembraneDiffusion1DSolver,
    MultiLayerMembraneSolver,
    renkin_hindrance,
    # Submodules
    dimensionless,
    analytical,
    # Fluid dynamics (Stokes & Navier-Stokes)
    VelocityBCType,
    VelocityBC,
    StokesResult,
    StokesSolver,
    ConvectionScheme,
    NavierStokesResult,
    NavierStokesSolver,
    # Cylindrical mesh
    CylindricalMeshType,
    CylindricalMesh,
    # Non-Newtonian fluid models
    FluidModel,
    ViscosityModel,
    NewtonianModel,
    PowerLawModel,
    CarreauModel,
    CarreauYasudaModel,
    CrossModel,
    BinghamModel,
    HerschelBulkleyModel,
    CassonModel,
    # Blood rheology utilities
    blood_casson_model,
    blood_carreau_model,
    pipe_wall_shear_rate,
    apparent_viscosity_pipe,
    # I/O and visualization
    write_vtk,
    write_vtk_series,
    write_vtk_series_with_metadata,
    # Multi-species reaction-diffusion
    MultiSpeciesSolver,
    LotkaVolterraReaction,
    SIRReaction,
    SEIRReaction,
    BrusselatorReaction,
    CompetitiveInhibitionReaction,
    EnzymeCascadeReaction,
    # Nernst-Planck electrochemical transport
    IonSpecies,
    NernstPlanckSolver,
    MultiIonSolver,
    # Nernst-Planck submodules
    constants,
    ions,
    ghk,
)

__all__ = [
    "BalanceDimension",
    "BalanceUnit",
    "BalanceTransferDirection",
    "BalanceTerm",
    "BalanceTransfer",
    "BalanceAudit",
    "BalanceLedger",
    "MatchedBalanceTransfer",
    "DimensionBalanceAudit",
    "BalanceReconciliation",
    "balance_dimension_name",
    "balance_unit_symbol",
    "balance_unit_dimension",
    "balance_base_unit",
    "convert_balance_value",
    "reconcile_balances",
    "native_build_info",
    "NonuniformMesh1D",
    "NonuniformDiffusionDiagnostics",
    "NonuniformDiffusion1D",
    "StructuredMesh",
    "StructuredMesh3D",
    "Boundary3D",
    "DiffusionSolver",
    "DiffusionSolver3D",
    "LinearReactionDiffusionSolver3D",
    "CrankNicolsonDiffusion",
    "CNSolveResult",
    # ADI solvers
    "ADIDiffusion2D",
    "ADIDiffusion3D",
    "ADISolveResult",
    # Sparse matrix and implicit solvers
    "SparseSolverType",
    "SparseSolveResult",
    "Triplet",
    "SparseMatrix",
    "build_2d_laplacian",
    "build_implicit_diffusion_2d",
    "build_implicit_diffusion_3d",
    "ImplicitSolveResult",
    "ImplicitDiffusion2D",
    "ImplicitDiffusion3D",
    "sparse_matrix_available",
    "ConstantSourceReactionDiffusionSolver",
    "LinearReactionDiffusionSolver",
    "LogisticReactionDiffusionSolver",
    "MichaelisMentenReactionDiffusionSolver",
    "ReactionDiffusionSolver",
    "MaskedMichaelisMentenReactionDiffusionSolver",
    "BoundaryType",
    "Boundary",
    "BoundaryCondition",
    "TransportProblem",
    "ExplicitFD",
    "RunResult",
    "GrayScottSolver",
    "GrayScottRunResult",
    "TumorDrugDeliverySolver",
    "TumorDrugDeliverySaved",
    "BioheatCryotherapySolver",
    "BioheatSaved",
    "SolverStats",
    "SolveOptions",
    "SolveDiagnostics",
    "TransportResult",
    "solve_transport",
    # Higher-order finite difference stencils
    "StencilOps",
    "AdvectionScheme",
    "AdvectionDiffusionSolver",
    "DarcyFlowResult",
    "DarcyFlowSolver",
    "MembraneDiffusionResult",
    "MembraneDiffusion1DSolver",
    "MultiLayerMembraneSolver",
    "renkin_hindrance",
    "dimensionless",
    "analytical",
    # Fluid dynamics (Stokes & Navier-Stokes)
    "VelocityBCType",
    "VelocityBC",
    "StokesResult",
    "StokesSolver",
    "ConvectionScheme",
    "NavierStokesResult",
    "NavierStokesSolver",
    # Cylindrical mesh
    "CylindricalMeshType",
    "CylindricalMesh",
    # Non-Newtonian fluid models
    "FluidModel",
    "ViscosityModel",
    "NewtonianModel",
    "PowerLawModel",
    "CarreauModel",
    "CarreauYasudaModel",
    "CrossModel",
    "BinghamModel",
    "HerschelBulkleyModel",
    "CassonModel",
    # Blood rheology utilities
    "blood_casson_model",
    "blood_carreau_model",
    "pipe_wall_shear_rate",
    "apparent_viscosity_pipe",
    # I/O and visualization
    "write_vtk",
    "write_vtk_series",
    "write_vtk_series_with_metadata",
    # Multi-species reaction-diffusion
    "MultiSpeciesSolver",
    "LotkaVolterraReaction",
    "SIRReaction",
    "SEIRReaction",
    "BrusselatorReaction",
    "CompetitiveInhibitionReaction",
    "EnzymeCascadeReaction",
    # Nernst-Planck electrochemical transport
    "IonSpecies",
    "NernstPlanckSolver",
    "MultiIonSolver",
    "constants",
    "ions",
    "ghk",
]
