"""Scalar transport and diffusion APIs, organized for discovery.

The canonical :class:`TransportProblem` plus :func:`solve` path runs the
conservation-form native solver.  The remaining classes are explicit,
specialized interfaces with their own equation, boundary-condition, and
stability contracts.  Importing them from this namespace does not make those
contracts interchangeable.

This module only re-exports existing public objects; it implements no
discretization or time stepping.
"""

from ._core import (
    ADIDiffusion2D,
    ADIDiffusion3D,
    ADISolveResult,
    AdvectionDiffusionSolver,
    AdvectionScheme,
    Boundary,
    Boundary3D,
    BoundaryCondition,
    BoundaryType,
    BrusselatorReaction,
    CNSolveResult,
    ConstantSourceReactionDiffusionSolver,
    CompetitiveInhibitionReaction,
    CrankNicolsonDiffusion,
    DiffusionSolver,
    DiffusionSolver3D,
    EnzymeCascadeReaction,
    GrayScottRunResult,
    GrayScottSolver,
    ImplicitDiffusion2D,
    ImplicitDiffusion3D,
    ImplicitSolveResult,
    LinearReactionDiffusionSolver,
    LinearReactionDiffusionSolver3D,
    LogisticReactionDiffusionSolver,
    LotkaVolterraReaction,
    MaskedMichaelisMentenReactionDiffusionSolver,
    MembraneDiffusion1DSolver,
    MembraneDiffusionResult,
    MichaelisMentenReactionDiffusionSolver,
    MultiLayerMembraneSolver,
    MultiSpeciesSolver,
    NonuniformDiffusion1D,
    NonuniformDiffusionDiagnostics,
    NonuniformMesh1D,
    ReactionDiffusionSolver,
    SEIRReaction,
    SIRReaction,
    SolveDiagnostics,
    SolveOptions,
    SparseSolverType,
    StructuredMesh,
    StructuredMesh3D,
    TransportProblem,
    TransportResult,
    renkin_hindrance,
    solve_transport,
)
from .mesh_utils import mesh_1d, mesh_2d, x_nodes, xy_grid, y_nodes
from .run import solve

__all__ = [
    # Meshes and boundary data
    "StructuredMesh",
    "StructuredMesh3D",
    "NonuniformMesh1D",
    "Boundary",
    "Boundary3D",
    "BoundaryType",
    "BoundaryCondition",
    "mesh_1d",
    "mesh_2d",
    "x_nodes",
    "y_nodes",
    "xy_grid",
    # Canonical scalar transport
    "TransportProblem",
    "SolveOptions",
    "SolveDiagnostics",
    "TransportResult",
    "solve_transport",
    "solve",
    # Specialized diffusion algorithms
    "DiffusionSolver",
    "DiffusionSolver3D",
    "LinearReactionDiffusionSolver3D",
    "CrankNicolsonDiffusion",
    "CNSolveResult",
    "ADIDiffusion2D",
    "ADIDiffusion3D",
    "ADISolveResult",
    "SparseSolverType",
    "ImplicitDiffusion2D",
    "ImplicitDiffusion3D",
    "ImplicitSolveResult",
    "NonuniformDiffusion1D",
    "NonuniformDiffusionDiagnostics",
    # Advection and reaction-diffusion
    "AdvectionScheme",
    "AdvectionDiffusionSolver",
    "ReactionDiffusionSolver",
    "ConstantSourceReactionDiffusionSolver",
    "LinearReactionDiffusionSolver",
    "LogisticReactionDiffusionSolver",
    "MichaelisMentenReactionDiffusionSolver",
    "MaskedMichaelisMentenReactionDiffusionSolver",
    "MultiSpeciesSolver",
    "LotkaVolterraReaction",
    "SIRReaction",
    "SEIRReaction",
    "BrusselatorReaction",
    "CompetitiveInhibitionReaction",
    "EnzymeCascadeReaction",
    "GrayScottSolver",
    "GrayScottRunResult",
    # Steady membrane diffusion and hindrance
    "MembraneDiffusion1DSolver",
    "MultiLayerMembraneSolver",
    "MembraneDiffusionResult",
    "renkin_hindrance",
]
